# stage 1: copy the source and build the app

FROM node:16-alpine3.11 AS builder

WORKDIR /trainscoding-tests

COPY ../../services /trainscoding-tests/services
COPY ../../packages /trainscoding-tests/packages
COPY ../../package.json /trainscoding-tests
COPY ../../package-lock.json /trainscoding-tests
COPY ../../lerna.json /trainscoding-tests
COPY ../../tsconfig.json /trainscoding-tests
COPY ../../babel.config.js /trainscoding-tests
COPY ../../jest.config.ts /trainscoding-tests

RUN npm i

CMD [ "npm", "test" ]
