version: "3.9"

services:
  server:
    image: javiergarciagon/trainscoding-server:0.0.4
    environment:
      SERVER_PORT: ${SERVER_PORT}
    env_file:
    - ./services/server/.env.server
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    command: ["npm", "start"]
