PROJECT_NAME := trainscoding

ROOT_DIR := $(abspath .)

MAIN_DOCKER_COMPOSE := docker-compose -f docker-compose.yml
TEST_DOCKER_COMPOSE := docker-compose -f docker/docker-compose-unit-tests.yml

ADDITIONAL_ENV_FILES_FOR_DEVELOPMENT :=
