PROJECT_NAME := trainscoding

ROOT_DIR := $(abspath .)

MAIN_DOCKER_COMPOSE := docker-compose -f docker/environment/development/docker-compose.yml
TEST_DOCKER_COMPOSE := docker-compose -f docker/environment/test/docker-compose-unit-tests.yml
SCOPED_TEST_DOCKER_COMPOSE := docker-compose -f docker/environment/test/docker-compose-unit-tests-scoped.yml

ADDITIONAL_ENV_FILES_FOR_DEVELOPMENT :=
