FROM node:16-alpine3.11

WORKDIR /trainscoding-tests

COPY services /trainscoding-tests/services
COPY packages /trainscoding-tests/packages
COPY package.json /trainscoding-tests
COPY package-lock.json /trainscoding-tests
COPY lerna.json /trainscoding-tests
COPY babel.config.js /trainscoding-tests
COPY jest.base.config.js /trainscoding-tests
COPY jest.config.js /trainscoding-tests

RUN npm ci

CMD [ "npm", "test" ]
