# stage 1: copy the source and build the app

FROM node:16-alpine3.11 AS builder

WORKDIR /dist

COPY ../services /dist/services
COPY ../packages /dist/packages
COPY ../package.json /dist
COPY ../package-lock.json /dist
COPY ../lerna.json /dist
COPY ../tsconfig.json /dist
COPY ../babel.config.js /dist
COPY ../jest.config.ts /dist

RUN set -eux ; \
  npm i ; \
  npm run build

# stage 2: copy the output and run it in production

FROM node:16-alpine3.11

WORKDIR /usr/trainscoding

ENV NODE_ENV=production

COPY --from=builder /dist/package*.json /usr/trainscoding
COPY --from=builder /dist /usr/trainscoding

CMD [ "npm", "test" ]
